package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"log"

	"github.com/gqlgensamples/golang-gqlgen-postgresql-example/graph/model"
)

// OfferList is the resolver for the OfferList field.
func (r *queryResolver) OfferList(ctx context.Context, id string) (*model.OfferList, error) {
	offerlist, err := r.Repo.OfferList.GetOfferList(ctx, id)
	if err != nil {
		log.Print("failed to get offerlist")
		return nil, err
	}

	output := &model.OfferList{
		ID:   offerlist.ID,
		Name: offerlist.Name,
	}

	return output, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
